### ISSUE TITLE
application info

### ISSUE THREAD

**Issue by pin32** [dj-nitehawk/Hybrid-Inverter-Monitor#15]
howdy. I accidentally found this job doing research and it seems to me to be my case. I would like some information if possible. The application allows you to control Voltronic inverters via MQTT or just monitor?. I should use it on RPI4 with Openhab home automation server, and I would like to send commands to the inverter. Thanks for any answers. Joseph

**Comment by dj-nitehawk** [comment]
this app is designed to be self hosted on any linux computer even a RPI or any other SBC such as an orange-pi.
and it has no dependencies on any third party services such as MQTT or anything else.
it can monitor and have some control over inverters that support the voltronic protocol.
see the interface here: https://streamable.com/iggtlp
