### ISSUE TITLE
Build documentation

### ISSUE THREAD

**Issue by Saentist** [dj-nitehawk/Hybrid-Inverter-Monitor#2]
Is it possible to be added simple steps for building binary 
needed dependencies etc.

I try to build it on  AlpinLinux 32bit without success.

[Matching /dev/hidraw* devices with physical devices](https://arvchristos.github.io/post/matching-dev-hidraw-devices-with-physical-devices/)
```bash
#!/bin/bash

FILES=/dev/hidraw*
for f in $FILES
do
  FILE=${f##*/}
  DEVICE="$(cat /sys/class/hidraw/${FILE}/device/uevent | grep HID_NAME | cut -d '=' -f2)"
  printf "%s \t %s\n" $FILE "$DEVICE"
done
```

**Comment by dj-nitehawk** [comment]
alpine deps for .net:
https://docs.microsoft.com/en-us/dotnet/core/install/linux-alpine

after installing the deps and then .net sdk, try to publish the `InverterMon.Server` project with following:
```
dotnet publish -r linux-musl-arm --self-contained
```
can't help you anymore than that as i don't have a 32bit alpine device to try stuff on.

**Comment by dj-nitehawk** [comment]
i added an automated build pipeline which produces for a couple of common linux architectures.
try them out to see if it works with your arch: https://github.com/dj-nitehawk/Hybrid-Inverter-Monitor/releases/tag/v1.2

**Comment by dj-nitehawk** [comment]
aparrantly `dotnet publish` does not support building for linux-x86 out of the box.
didn't find much clear info on how to do it for 32bit alpine.
most likely you'd have to build the whole .net sdk yourself.
will keep you posted if i find the proper way to do it.
