### ISSUE TITLE
illegal instruction

### ISSUE THREAD

**Issue by jmcastillejo** [dj-nitehawk/Hybrid-Inverter-Monitor#20]
when I run the program on a raspberry pi zero it gives the error illegal instruction.

**Comment by Saentist** [comment]
Any log from manual run?
Do you run it as SuperUser?

**Comment by jmcastillejo** [comment]
In superuser give same error
how exec manual run? I exec sudo ./InverterMon.Server

**Comment by dj-nitehawk** [comment]
try the linux-arm 32 bit binaries: https://github.com/dj-nitehawk/Hybrid-Inverter-Monitor/releases/download/v1.17/linux-arm.zip

if that doesn't work, i'm afraid you need a device that has a ARMv7 cpu.
this app is written using .net 7.0 which requires ARMv7 or newer.
i believe the pi zero is ARMv6 :-(
