### ISSUE TITLE
ARMv6 support?

### ISSUE THREAD

**Issue by j-broo** [dj-nitehawk/Hybrid-Inverter-Monitor#21]
Any chance this could be built/modded to support ARMv6? I have an older Raspberry Pi and get an Illegal Instruction error trying to run the ARM build, so assume it's built for v7 or later.

**Comment by j-broo** [comment]
dpkg --print architecture reports "armhf". Is there any hope at all?

**Comment by dj-nitehawk** [comment]
i'm afraid not...
pls see my answer here: https://github.com/dj-nitehawk/Hybrid-Inverter-Monitor/issues/20#issuecomment-1509492786
