### ISSUE TITLE
Support for x86

### ISSUE THREAD

**Issue by timebis** [dj-nitehawk/Hybrid-Inverter-Monitor#22]
Hi,
thanks for all the work that has been made !
Do you have a binary that is supported by i686 32-bit ?
Best regards

**Comment by Saentist** [comment]
dotNet used, do not support x86 32 bit.

**Comment by dj-nitehawk** [comment]
like @Saentist said, the app is written in .net which only supports a few 32bit architectures such as: arm 32bit, muscl-arm 32bit
what's the cpu architecture of your device? best bet would be arm v7 or newer.

**Comment by timebis** [comment]
thanks for the answer !
