### ISSUE TITLE
How to send a news by SSE  to every browser clients? 

### ISSUE THREAD

**Issue by bobbydog** [dj-nitehawk/Hybrid-Inverter-Monitor#25]
This SSE example Endpoint GetStatus ,  I wonder when there are more than two browser clients subsribed "status",  the code is seemed to be  the CommandQueue.GetCommand() method will just Peek one comand  for the one client to comsume, yet others won't get response ?

**Comment by dj-nitehawk** [comment]
there is no SSE being used. it's just an http stream (done via `IAsyncEnumerable`):

https://github.com/dj-nitehawk/Hybrid-Inverter-Monitor/blob/6ea7af8b5c78c423c7075c0ff4b9d9cda93aebb7/src/Server/Endpoints/GetStatus/Endpoint.cs#L19-L22

also the endpoint does not cause a [GetStatus Command](https://github.com/dj-nitehawk/Hybrid-Inverter-Monitor/blob/main/src/Server/InverterService/Commands/GetStatus.cs) to be issued to the inverter per browser client.

it sends the same status data to all connected browsers.

reading the status data from the inverter is done by a [background service](https://github.com/dj-nitehawk/Hybrid-Inverter-Monitor/blob/main/src/Server/InverterService/StatusRetriever.cs) which queues `GetStatus Command`s which queues the `QPIGS` command every 2 seconds.

there's a separate [background service](https://github.com/dj-nitehawk/Hybrid-Inverter-Monitor/blob/main/src/Server/InverterService/CommandExecutor.cs) for the main queue (which stores all type of commands) and executes them serially.

the architecture is a bit difficult to understand but that's the only way i found to query data from the inverter and distribute that data to multiple client browsers in a reliable way.
