### ISSUE TITLE
sumry hybrid inverter is supported?

### ISSUE THREAD

**Issue by hoangkhacchung** [dj-nitehawk/Hybrid-Inverter-Monitor#31]
I try connecting to sumry hybrid inverter but it is not working.  sumry hybrid inverter is supported? Thanks,

**Comment by dj-nitehawk** [comment]
is it a voltronic clone inverter?
does it work with the watchpower app via usb cable?
if so, it should theoretically work.
can't offer any more help than that as i'm not familiar with sumry brand.

**Comment by Saentist** [comment]
@dj-nitehawk 
enable discussion module in repo for "question's"

**Comment by dj-nitehawk** [comment]
@Saentist got too many things to manage already. it's ok if ppl wanna ask questions in gh issues ;-)

**Comment by Saentist** [comment]
@dj-nitehawk discussion is for that ;)
can be made section "supported/tested inverters"
easy for all, after some time issue will be closed and hard to find needed information.
