### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by sanatho** [dj-nitehawk/Hybrid-Inverter-Monitor#7]
When I execute InverterMon.Server I get this error 
![image](https://user-images.githubusercontent.com/70145951/196192240-d1493444-1131-4584-a83d-69af0ac39a55.png)
ice.CommandExecutor[0]
OS: raspian os lite (64 bit)
Device: Raspberry pi 3b+

**Comment by dj-nitehawk** [comment]
execute `lsusb` in your terminal.
see if there's a device like the following:
```cs
Bus 005 Device 002: ID 0665:5161 Cypress Semiconductor USB to Serial
```
if a device does exist, do the following and determine where the hidraw device is mounted:
```cs
ls /dev/hid*
```
if the hidraw number is not 0, you gotta update the `appsettings.json` file with the correct path to the device.

**Comment by sanatho** [comment]
![image](https://user-images.githubusercontent.com/70145951/196193839-aee15e5d-c0ad-44ab-beed-760949c79645.png)
I see this device

**Comment by sanatho** [comment]
![image](https://user-images.githubusercontent.com/70145951/196194219-9f806e4d-2de7-460d-a08a-19f66d9a3140.png)

when i execute the server for the first time i see the info for 1 second and after  i get the error

**Comment by dj-nitehawk** [comment]
when connection breaks, does the `/dev/hidraw0` device also disappear from the os?
could be a loose usb connection/port issue.
does it work correctly for watchpower app?

**Comment by sanatho** [comment]
I have never encountered any problems in watchpower app

**Comment by dj-nitehawk** [comment]
and what is the brand/model of your inverter?
does it support the voltronic protocol?

**Comment by sanatho** [comment]
this appear when i execute the server for the first time
![image](https://user-images.githubusercontent.com/70145951/196195852-119140d0-5d08-47a9-a945-c0dc7dbe07d1.png)
the device doesn't disappear
![image](https://user-images.githubusercontent.com/70145951/196196208-9f216255-b544-49d3-b2f3-e9136ec9ab30.png)
the inverter is inxii 3000w (i think that support voltronic protocol because i see info the first time)

**Comment by dj-nitehawk** [comment]
are you connecting to the raspi via wifi? if so, can you try connecting with ethernet instead?
if still no after trying that, i'm afraid there's no way for me to debug the issue without having physical access to your inverter.
unless you know some C# and willing to do the debugging yourself using the source code.

**Comment by sanatho** [comment]
I am connected via wifi and i and i can't connect via ethernet. maybe i could try to understand c#

**Comment by dj-nitehawk** [comment]
also try holding the usb port in a fixed position on the inverter without letting go. those chinese clone inverters sometimes have loose connection ports. i have no idea why the connection breaks after initial success.

**Comment by dj-nitehawk** [comment]
also i've had similar experience with raspi and built-in wifi. after using a wifi dongle, the situation became better.

**Comment by sanatho** [comment]
the strange thing is that the original program does not give any problems

**Comment by dj-nitehawk** [comment]
yes strange indeed.

**Comment by sanatho** [comment]
Thanks for your suggestions

**Comment by Saentist** [comment]
@sanatho 
See if DMESG show some strange messages when this happens.

My suggestion is, that there is electrical grounding problem.

**Comment by dj-nitehawk** [comment]
@Saentist can a grounding issue cause interference with serial data communication?

**Comment by sanatho** [comment]
Could low power supply be a problem?

**Comment by dj-nitehawk** [comment]
insufficient power may also be a cause. i've had both wifi and usb connection dropouts with raspi b3+
switched to an orange pi 4 lts and been problem free since ;-)
